name: 'Rust backwards incompatible labeler'
author: 'Patrick Uiterwijk'
description: 'Label PRs that are backwards incompatible with a specific label'
inputs:
  dnf-dependencies:
    description: 'Fedora packages your compile depends on'
    # This is just one that we know will be there
    default: 'rpm'
  runner-image:
    description: 'Name of the image to use, leave blank normally'
    default: 'docker://docker.pkg.github.com/puiterwijk/action-label-rust-incompatible/runner:latest'
  repo-token:
    description: 'API token to use when tagging'
    required: true
  label-patch:
    description: 'Label to apply to patch PRs'
    required: false
  label-non-breaking:
    description: 'Label to apply to non-breaking PRs'
    required: false
  label-technically-breaking:
    description: 'Label to apply to technically breaking PRs'
    required: false
  label-breaking:
    description: 'Label to apply to breaking PRs'
    required: false
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    repo_token: ${{ inputs.repo-token }}
    dnf_dependencies: ${{ inputs.dnf-dependencies }}
    LABEL_PATCH: ${{ inputs.label-patch }}
    LABEL_NON_BREAKING: ${{ inputs.label-non-breaking }}
    LABEL_TEHNICALLY_BREAKING: ${{ inputs.label-technicaly-breaking }}
    LABEL_BREAKING: ${{ inputs.label-breaking }}
branding:
  icon: 'tag'
  color: 'green'
