name: Build and push

on:
  - push
  - pull_request

jobs:
  compile_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "docker.pkg.github.com/puiterwijk/action-label-rust-incompatible/action:latest"
      - if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: "action-label-rust-incompatible:test"
