name: Compile and push

on:
  - push

jobs:
  compile_and_push:
    name: Compile and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Test
      - uses: puiterwijk/action-label-rust-incompatible@wip
        with:
          dnf-dependencies: 'dnf'
          runner-image: 'Dockerfile'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          label-patch: "API/Patch"
          label-non-breaking: "API/Non-Breaking"
          label-technically-breaking: "API/Technically-Breaking"
          label-breaking: "API/Breaking"
      # Compile/push
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/setup-buildx-action@v1
      - if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # TODO: Only do if we're on release tag
      - if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "docker.pkg.github.com/puiterwijk/action-label-rust-incompatible/action:latest"
