name: Selftest

on:
  - push
  - pull_request

jobs:
  compile_and_push:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-and-push-action@v2
        with:
          push: true
          tags:
          - docker.pkg.github.com/puiterwijk/action-label-rust-incompatible
